version: '3'

services:
    web:
        build:
            context: .
            dockerfile: docker/Dockerfile
        image: covidapp
        ports:
            - "5050:80"
        links:
            - mysql:db
        volumes:
            - .:/app
    mysql:
        image: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=covidapp
            - MYSQL_PASSWORD=meilleurmdpaumonde
            - MYSQL_DATABASE=covidapp
        volumes:
            - ./mysqldata:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "5051:80"
        links:
            - mysql:db
