version: '2'

services:
    web:
        image: covidapp
        ports:
            - "5050:80"
        links:
            - mysql:db
        volumes:
            - .:/app
    mysql:
        image: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=meilleurmdpaumonde
            - MYSQL_DATABASE=covidapp
        volumes:
            - ./mysqldata:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "5051:80"
        links:
            - mysql:db